### ISSUE TITLE
SendAuthRequest: "Error: Invalid response: 503"

### ISSUE THREAD

**Issue by FranciscoHanna** [TodoPago/SDK-Node.js#17]
## Comportamiento esperado
Obtener el objeto de respuesta de SendAuthRequest para hacer la redirección al formulario de pago.

## Comportamiento actual
Al invocar el metodo `sendAutorizeRequest`, la respuesta es:
```
Error: Invalid response: 503
Body: <?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><api:SendAuthorizeRequestResponse xmlns:api="http://api.todopago.com.ar"><api:StatusCode></api:StatusCode><api:StatusMessage></api:StatusMessage><api:URL_Request></api:URL_Request><api:RequestKey></api:RequestKey><api:PublicRequestKey></api:PublicRequestKey></api:SendAuthorizeRequestResponse></soapenv:Body></soapenv:Envelope>
    at /home/franciscohanna92/white-label-b-site-node/lib/todopago/node_modules/soap/lib/client.js:174:16
    at Request._callback (/home/franciscohanna92/white-label-b-site-node/lib/todopago/node_modules/soap/lib/http.js:60:7)
    at Request.self.callback (/home/franciscohanna92/white-label-b-site-node/lib/todopago/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/franciscohanna92/white-label-b-site-node/lib/todopago/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/franciscohanna92/white-label-b-site-node/lib/todopago/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
```

## Pasos a reproducir
Ejecutar el siguiente codigo:
```javascript
var sdk = require('../lib/todopago/');
var options = {
	endpoint : 'developers',
	Authorization:'PRISMA A793D307441615AF6AAAD7497A75DE59'
};

var parameters = {
    'Session': 'ABCDEF-1234-12221-FDE1-00000200',
    'Security': 'A793D307441615AF6AAAD7497A75DE59',
    'EncodingMethod': 'XML',
    'MERCHANT': 2159,
    'URL_OK': 'http://localhost:3000/booking/success',
    'URL_ERROR': 'http://localhost:3000/booking/error',
    'MERCHANT': "2153",
    'OPERATIONID': "60",
    'CURRENCYCODE': "032",
    'AMOUNT': "54",
    'MAXINSTALLMENTS': "3",
    'MAXINSTALLMENTS': "12"
};

var fraudControl = {
    'CSBTCITY': 'Villa General Belgrano',
    'CSBTCOUNTRY': 'AR',
    'CSBTEMAIL': 'todopago@hotmail.com',
    'CSBTFIRSTNAME': 'Juan',
    'CSBTLASTNAME': 'Perez',
    'CSBTPHONENUMBER': '541160913988',
    'CSBTPOSTALCODE': ' 1010',
    'CSBTSTATE': 'B',
    'CSBTSTREET1': 'Cerrito 740',

    'CSBTCUSTOMERID': '453458',
    'CSBTIPADDRESS': '192.0.0.4',
    'CSPTCURRENCY': 'ARS',
    'CSPTGRANDTOTALAMOUNT': '99.00',
    'CSMDD7': '',
    'CSMDD8': 'Y',
    'CSMDD9': '',
    'CSMDD10': '',
    'CSMDD11': '',
    'CSMDD12': '',
    'CSMDD13': '',
    'CSMDD14': '',
    'CSMDD15': '',
    'CSMDD16': '',
    'CSITPRODUCTCODE': 'electronic_good#chocho',
    'CSITPRODUCTDESCRIPTION': 'NOTEBOOK L845 SP4304LA DF TOSHIBA#chocho',
    'CSITPRODUCTNAME': 'NOTEBOOK L845 SP4304LA DF TOSHIBA#chocho',
    'CSITPRODUCTSKU': 'LEVJNSL36GN#chocho',
    'CSITTOTALAMOUNT': '1254.40#10.00',
    'CSITQUANTITY': '1#1',
    'CSITUNITPRICE': '1254.40#15.00'
};

function sendAuthRequest() {
    sdk.sendAutorizeRequest(options, parameters, fraudControl, function (result, err) {
        if(err) {
            console.log(err);
        }
        else {
            console.log(result);
        }
    });
}

sendAuthRequest();
```

## Entorno
+ Entorno
  * __SO:__ Ubuntu 16.04 x64
  * __Servidor Web y versión:__ Node 8.6 + Express 4.0
  * __Versión de TodoPago:__ 1.4.0
  * __Ambiente de Todopago:__ Prueba

**Comment by FranciscoHanna** [comment]
Fue un error mio. En el objeto `parameters` olvide de setear la propiedad `MERCHANT` con el merchant ID correcto. 
De cualquier manera pienso que tener una propiedad repetida (`Merchant` y `MERCHANT`) es una mala práctica y un diseño de interfaz pobre, que lleva a errores ingenuos.
